#!/usr/bin/env python
# coding=utf-8
"""fit_traj_Escalar: recover a scalar global Young's modulus E from a trajectory.

v0 is either FIXED to GT (--fix-v0, isolates E) or estimated first in a velocity
warmup stage (two-stage sequential: vel learns v0, then phys learns E). GT is
generated by GIC's own simulator under the chosen GT params; geometry loss only.

The scalar-E slice of the old roundtrip_ours_scene. Field E -> fit_traj_Efield;
v0 recovery -> fit_traj_v0; joint v0+E -> fit_traj_joint; image loss -> fit_image_*.

Usage (gic env, gic repo root) -- run the entrypoint directly, tyro parses args;
the run dir is auto-placed at output/fit_traj_Escalar/<NN>_<label>/:
  python fit_traj_Escalar.py --scene.cache <cache.pt> --gt.log-e 5.0 \
      --init-log-e 6.0 --run-label gtE5_initE6              # two-stage
  python fit_traj_Escalar.py --scene.cache <cache.pt> --gt.log-e 5.0 \
      --init-log-e 6.0 --fix-v0                             # E-only
"""
from ours.gpu import pick_gpu

pick_gpu()  # pick a free GPU before torch/taichi create a CUDA context

import json
import math
import time
from dataclasses import dataclass, field
from typing import Optional

import torch
import tyro

from simulator import Estimator
from utils.system_utils import draw_curve

from ours.config import FramesCfg, GTCfg, SceneCfg, TrainCfg, make_phys_args
from ours.rundir import RunDir
from ours.scene import build_anchored_scene, rollout_collect_surfaces, set_params
from ours.train import train_ours
from ours.viz import plot_axis_profiles, plot_param_traj, save_overlay_gif, save_rollout_gif


@dataclass
class Config:
    scene: SceneCfg
    gt: GTCfg = field(default_factory=GTCfg)
    train: TrainCfg = field(default_factory=TrainCfg)
    frames: FramesCfg = field(default_factory=FramesCfg)
    init_logE: float = 6.0
    init_nu: float = 0.1
    fix_v0: bool = False
    """fix v0 to gt.vel and skip the velocity stage (isolate E)"""
    E_lr: Optional[float] = None
    nu_lr: Optional[float] = None
    run_label: str = ""
    out: Optional[str] = None
    """override the auto run dir (scratch escape hatch)"""


def run(cfg: Config, rd: RunDir) -> None:
    start = time.time()
    phys_args = make_phys_args(cfg.scene, cfg.train, cfg.frames,
                               cfg.init_logE, cfg.init_nu, cfg.E_lr, cfg.nu_lr)
    n_frames = phys_args.n_frames if cfg.frames.n_frames is None else cfg.frames.n_frames
    phys_args.n_frames = n_frames

    scene = build_anchored_scene(cfg.scene.cache, cfg.scene.rot_z_deg, phys_args,
                                 cfg.scene.anchor_mass_scale, n_frames,
                                 inject_pvol=cfg.scene.inject_pvol,
                                 ti_mem_frac=cfg.scene.ti_mem_frac)
    est, xyz, free = scene["est"], scene["xyz"], scene["free"]
    print(f"[Escalar] N={xyz.shape[0]}, anchors={int((~free).sum())}, "
          f"dx={phys_args.voxel_size}, fix_v0={cfg.fix_v0}")

    # ---- 1. GT: generate with GIC's own simulator ----
    set_params(est, cfg.gt.logE, cfg.gt.nu, list(cfg.gt.vel))
    gts = rollout_collect_surfaces(est)
    disp = (gts[-1] - gts[0]).norm(dim=-1)
    print(f"[Escalar] GT motion: free mean disp {disp[free].mean():.5f}, "
          f"max {disp[free].max():.5f}; anchor mean {disp[~free].mean():.6f} (~0)")
    save_rollout_gif(gts, rd.path("gt_rollout.gif"))

    # ---- 2. refit from init ----
    est.gts = gts
    est.load_gts(gts)
    fit_v0 = list(cfg.gt.vel) if cfg.fix_v0 else list(phys_args.init_vel)
    set_params(est, cfg.init_logE, cfg.init_nu, fit_v0)
    losses_vel, e_s_vel = [], []
    if cfg.fix_v0:
        phys_args.vel_iter_cnt = 0
    else:  # two-stage: velocity warmup, then physical params
        est.set_stage(Estimator.velocity_stage)
        losses_vel, e_s_vel = train_ours(
            est, phys_args, phys_args.vel_estimation_frames, rd.root, gts=gts,
            patience=cfg.train.patience, min_iters=cfg.train.min_iters,
            ckpt_every=cfg.train.ckpt_every, overlay_every=cfg.train.overlay_every,
            param_stop_tol=cfg.train.param_stop_tol)

    phys_frames = cfg.frames.phys_frames if cfg.frames.phys_frames is not None else n_frames
    est.set_stage(Estimator.physical_params_stage)
    losses_phys, e_s_phys = train_ours(
        est, phys_args, phys_frames, rd.root, gts=gts,
        patience=cfg.train.patience, min_iters=cfg.train.min_iters,
        ckpt_every=cfg.train.ckpt_every, overlay_every=cfg.train.overlay_every,
        fine_lr=cfg.train.fine_lr)

    # ---- 3. export ----
    min_idx = losses_phys.index(min(losses_phys))
    best = e_s_phys[min_idx]
    gt_E = 10.0 ** cfg.gt.logE
    best_v0 = est.init_vel.detach().cpu().numpy().tolist()
    set_params(est, math.log10(best["Youngs modulus"]), best["Poisson ratio"], best_v0)
    est.max_f = n_frames
    pred = rollout_collect_surfaces(est)
    save_rollout_gif(pred, rd.path("pred_rollout.gif"))
    save_overlay_gif(gts, pred, rd.path("overlay.gif"), fit_frames=phys_frames)
    plot_axis_profiles(gts, pred, free, rd.path("axis_profile.png"), fit_frames=phys_frames)
    rel_err_E = abs(best["Youngs modulus"] - gt_E) / gt_E
    result = {
        "scenario": "ours_telephone_Escalar",
        "gt": {"E": gt_E, "logE": cfg.gt.logE, "nu": cfg.gt.nu, "vel": list(cfg.gt.vel)},
        "init": {"logE": cfg.init_logE, "nu": cfg.init_nu, "vel": fit_v0},
        "fix_v0": cfg.fix_v0,
        "best": {**best, "iter": min_idx, "loss": float(losses_phys[min_idx])},
        "final": e_s_phys[-1],
        "vel_estimated": est.init_vel.detach().cpu().numpy().tolist(),
        "rel_err_E": rel_err_E,
        "losses_vel": [float(l) for l in losses_vel],
        "losses_phys": [float(l) for l in losses_phys],
        "E_traj": [d.get("Youngs modulus") for d in e_s_phys],
        "nu_traj": [d.get("Poisson ratio") for d in e_s_phys],
        "v0_traj": [[float(x) for x in d["velocity"]] for d in e_s_vel
                    if "velocity" in d] or None,
        "gt_motion_free_mean_disp": float(disp[free].mean()),
        "gt_motion_free_max_disp": float(disp[free].max()),
        "gt_motion_anchor_mean_disp": float(disp[~free].mean()),
        "wall_time_s": time.time() - start,
    }
    with open(rd.path("result.json"), "w") as f:
        json.dump(result, f, indent=2)
    draw_curve(losses_phys, rd.root, name="loss_phys")
    if losses_vel:
        draw_curve(losses_vel, rd.root, name="loss_vel")
    plot_param_traj(e_s_phys, gt_E, cfg.gt.nu, rd.path("param_traj.png"))
    from ours.imgloss import build_panel
    build_panel(rd.root)
    print(f"[Escalar] DONE: GT E={gt_E:.3g} -> best E={best['Youngs modulus']:.3g} "
          f"(rel err {rel_err_E:.2%}), wall {time.time() - start:.0f}s -> {rd.root}")


def main() -> None:
    cfg = tyro.cli(Config)
    rd = RunDir.create(__name__, cfg.run_label, cfg.out, config=cfg)
    run(cfg, rd)


if __name__ == "__main__":
    main()
